title: pygal library
hero_image: images/banner.png
description: pygal-library description
version: 4
listed: false
ingredient: true
copyedit: false
last_tested: "2021-10-07"
steps:
  - title: pygal library