---
title: Utiliser la bibliothèque pygal
hero_image: images/banner.png
description: description bibliothèque-pygal
version: 4
listed: false
ingredient: true
copyedit: false
last_tested: "2021-10-07"
steps:
  - title: Utiliser la bibliothèque pygal
